module.exports = {
    "host": 'localhost',
    "port": 3008,
    "fullhost": '192.168.1.172:3008',
    'MAILSERVICE': {
        'NAME': 'Smtp',
        'HOST': 'smtp.gmail.com',
        'PORT': '465',
        'USER': 'endivesofttest@gmail.com', //'testrth1@gmail.com',
        'PASSWORD': 'endivetest2345' //'password',
    },
    'COUNTRYCODE': 'AU',
    'ADMINEMAIL': 'admin@hiremytrailer.com.au',
    'STRIPKEY': 'sk_test_PuqqcpkjkFrcMZcdlWEor4jc',
    'SECUREDSIGNINGAPIKEY': '00000Q108JW4KY9N9RO0U8DIQYTDGLRQ0URGUFYZQ3M0G00000000009PW',
    'SECUREDSIGNINGAPISECRETKEY': 'M4eritqzhIt7vT4/5LLCVHg/2MnIrPdrk3c5eDXndNP6/YPhT+nqMr4YzhbJdlQqURJAzXbuh5aUBsbx/vwjfw==',
    'SINCHAPIKEY': '4ebacec6-2866-45df-8dc2-304fed93d2f7',
    'SINCHSECRETKEY': 'gb8dRsrv9ESmumFs+mo/vA==',
    'CODES': {
        'OK': 200,
        'NoContent': 204,
        'BadRequest': 400,
        'Unauthorized': 401,
        'PR': 402,
        'Forbidden': 403,
        'notFound': 404,
        'Error': 500,
        'statusOk': 1,
        'statusFail': 0,
    },
    'MESSAGES': {
        'registerSuccess': 'Registered',
        'EmailAlreadyExist': 'Please recheck your email address. If you have forgotten your password? Select the Forgot Password link',
        'EmailNotExist': 'Please check your email for the link to update your password.',
        'updateSuccess': 'Updated',
        'saveSuccess': 'Saved',
        'Error': 'Error',
        'Success': 'Success',
        'statusSuccess': 'Status changed',
        'deleteSuccess': 'Deleted',
        'notFound': 'Not Found',
        'uploadSuccess': 'Uploaded',
        'valid': 'Valid',
        'invalid': 'Invalid',
        'passwordReset': 'A new password has been sent to your provided email address. Please check your email for the link to update your password.',
        'unAuthorizeAccess': 'Unauthorize Access',
        'resetInvalidToken': 'Invalid Token',
        'resetPasswordChanged': 'Password successfully changed',
        'checkEmailandPass': 'Please check your email and password',
        'checkPass': 'Please check your password',
        'emailNotVerify': 'Your email address has not been verified. Please check the email account you registered with.',
        'mobileNotVerify': 'Your mobile number has not been verified. Please check the mobile number you registered with.',
        'mobileEmailNotVerify': 'Your email and mobile number is not verified',
        'successLogin': 'You are successfully loggedIn',
        'emailVerify': 'Your email is successfully verified',
        'alredyBookedAndDelete': 'This trailer is already booked by renter, so you can`t be delete it.',
        'alredyBooked': 'This trailer is already booked by renter, so you can not book this trailer.',
        'alredyBookedAndUpdate': 'This trailer is already booked by renter, so you can not update or chnage status of the trailer.',
        'InvalidParameter': 'Invalid parameter',
        'ContactEmialMessage': 'Email has been sent to the administrator',
        'ratingMSG': 'Rating successfully Updated',
        'BookingRequest': 'Booking request sent successfully',
        'DefaultCardUpdated': 'Your default card set successfully',
        'SettingUpdate': 'Setting successfully updated',
        'notCardAddedd': "No such card added",
        'DBErr': "Database server error",
        'loginAttempt': 'Your account is currently suspended due to multiple incorrect login attempts. Please click on the Forgot Password link to reset your password.',
        'passwordResetTokenExpire': 'Your password reset token has been expired',
        'InvalidDate': 'Please select valid date.',
        'raiseDispute': 'You cannot book a trailer as a dispute is raised against you',
        'mobileVerifyBeforeBook': 'Please confirm you mobile number in the Profile Screen before proceeding',
        'completeProfileBeforeBook': 'Please complete your profile before proceeding',
        'mobileVerifyBeforeAddTrailer': 'Please confirm you mobile number in the Profile Screen before proceeding',
        'forgotpass': 'A new password has been sent to your provided email address. Please check your email for the link to update your password.',
        'OtpNotExist': 'The OTP you have entered is incorrect, please check your SMS and try again',
        'mobileExist': 'Please recheck the mobile number or visit the Help for assistance'
    }
};
